version: '3'

services:
  postgresql:
    image: postgres:13
    container_name: pgsql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app_api:
    image: backend:master
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      FAST_API_HOST: ${FAST_API_HOST}
      FAST_API_PORT: ${FAST_API_PORT}
      DBNAME: ${DBNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      RANDOM_SECRET: ${RANDOM_SECRET}
      TMDB_KEY: ${TMDB_KEY}
      MAIL_LOGIN: $(MAIL_LOGIN)
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - ${FAST_API_PORT}:${FAST_API_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  app_frontend:
    image: frontend:master
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${FAST_API_PORT}
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  postgres_data: